#!/usr/bin/env bash
# Transfers a file to a server user home directory using scp with custom SSH key. Strict host key checking is disabled.

if [ "$#" -ne 4 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

FILE_PATH="$1"
IP="$2"
USERNAME="$3"
SSH_KEY="$4"

scp -i "$SSH_KEY" -o StrictHostKeyChecking=no "$FILE_PATH" "${USERNAME}@${IP}:~/"

